### ISSUE TITLE
Investigate convergence jumps

### ISSUE THREAD

**Issue by Leirof** [Leirof/Tunable-Kernel-Nulling#33]
# Context

The convergeance process of the parameters is splitted in two steps:
- Step 1 : maximize the bright output $I_0$ by tuning the parameters 1, 2, 3, 4, 5 and 7
- Step 2 : maximize the symmetry between 2 paired outputs by minimizing $|I_1 - I_2| + |I_3 - I_4| + |I_5 - I_6|$

![components](https://github.com/Leirof/Tunable-Kernel-Nulling/assets/12165342/84ce9069-65ca-4153-81ac-55aa8156fefa)

To do so, one first inject 4 beams with a constant perturbation, and we run the convergence algorithm. Once the first step is done, all the flux is supposed to be redirected to the bright output, so no light remains in the split & mix part, which prevent to do the second step as the shifters will have no impact. To solve that, we perturb again the input beams which leads to introduce leakages and we run the convergeance algorithm using these new beams.

# Problem

Intuitively, the second step should not be sensitive to the input perturbations as these perturbations are cancelled when we make the difference between two paired outputs. However, we notice that if we introduce random input perturbations during the convergeance process, the convergence fail

![image](https://github.com/Leirof/Tunable-Kernel-Nulling/assets/12165342/57fa5512-c1a0-4cef-b7c8-a79764f0dcd1)

This leads us to two questions :
- Does this failure come from a code issue or from a physical process?
- If the failure come from a physical process and if we perform the second step using a constant perturbation, does the optimized shifters will still be in an optimal configuration for a new set of beams with different perturbations?

**Comment by rlaugier** [comment]
Interesting. I assume the perturbation you are introducing is small enough...

1. What algorithm are you using to converge? If it is smart enough it may be trying to build an inverse hessian, and modifying the system between iterations may mess with this process. If that is the problem, you have several options: i) simpler algorithm: like very dumb gradient descent. ii) let it converge for each perturbation state, then reset the algorithm when you change the perturbation. iii) consider a model where several observations for different perturbations are considered simultaneously in a concatenated observable vector.
2. This could also come from the fact that this balancing in the case of small errors in phase is only an approximation. To test this, you could try it with using amplitude offsets instead of phase offsets for your static perturbation...
